# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8318833d7204ab49a1a79f0d09082a93a39fdd464703e43e564f5335cf5a463271dbb4caddb3c667cf0ae9783e12070b570717053dc4e54dcd99d453199359f1

test:
  secret_key_base: 824ad27cf240f06f137003b09ec96a34ff3cec1ff61581761d321d350295148dd6477e7799d280d113b4560c35672cb1bfecbe7c86ec74c7e098bde532ecb4d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
